@startuml
'https://plantuml.com/class-diagram

title "Class diagram for Inventory"

class Inventory {
- content: Item[]
- numberOfPlace: int

----
+ getNumberOfPlace(): int
+ getNumberOfItems(): int
+ isFull(): boolean
+ isEmpty(): boolean
+ getNumberOfItems();
+ remove(indexPlace: int) throws NothingToRemoveException, ArrayIndexOutOfBoundsException
+ getFirstEmptySpace(): int
' Get the index of the first free space in the inventory
+ add(newItem: Item) throws InventoryFullException
+ add(indexPlace: int, newItem: Item) throws ArrayIndexOutOfBoundsException, NotEmptyPlaceException
+ getItemByIndex(indexPlace: int): Item throws ArrayIndexOutOfBoundsException
- relevantIndex(indexToCheck: int, numberOfPlace: int) throws ArrayIndexOutOfBoundsException

----
+ Inventory(nbOfPlaces: int)
}
note left : The player inventory

class Item {
- name: String
- desc: String
----
+ getName(): String
+ getDesc(): String
}
note right : Any object that a player can hold in its inventory


Inventory *-- Item


@enduml